openapi: 3.0.3
info:
  title: login-api
  version: 1.0.0
  description: Login
paths:
  /user/login:
    post:
      operationId: login
      tags:
      - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LoginRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
          description: ''
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        mail_address:
          type: string
          format: email
        password:
          type: string
          writeOnly: true
      required:
      - email
      - password
    LoginResponse:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
      required:
      - access
      - refresh
